apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::767397883495:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-hTaQECHMKKV7
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::767397883495:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2024-03-05T16:49:04Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1187"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: eb0c2963-24c0-4968-8b81-f0fc10dbefe4
