apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::767397883495:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-8lQ2zUliZrqs
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::767397883495:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2024-02-29T21:56:50Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1295"
  uid: 5cd2a27c-a8c0-454c-8079-278a70103478
